version: '3'

services:

  web:
    build: ./web
    networks:
      - nginx_network
    ports:
      - 8000:5000

  nginx:
    build: ./nginx
    ports:
      - 5000:80
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
